name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step to set up ROS 2 environment using ros-tooling/setup-ros
      - name: Setup ROS 2 Environment
        uses: ros-tooling/setup-ros@v0.7  # Pin to a specific version for stability
        with:
          required-ros-distributions: humble  # Install ROS 2 Humble distribution

      # Step to create and prepare the ROS 2 workspace
      - name: Set up ROS 2 Workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cd ~/ros2_ws/src

          # Clone the current repo into the src folder
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          mkdir $REPO_NAME
          cp -r $GITHUB_WORKSPACE/* $REPO_NAME/

          # Clone vortex-msgs repository into the src folder
          git clone https://github.com/vortexntnu/vortex-msgs.git

      # Install package dependencies using rosdep
      - name: Install Package Dependencies with rosdep
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # Build the workspace using colcon
      - name: Build ROS 2 Workspace
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          colcon build --event-handlers console_cohesion+

      # Run tests
      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          colcon test --event-handlers console_direct+

      # Show test results
      - name: Test Results Summary
        run: |
          cd ~/ros2_ws
          colcon test-result --verbose
