name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src

      - name: Import dependencies using vcs
        run: |
          ls -l
          mkdir -p ros2_ws/src  # Create the workspace structure
          cd ros2_ws
          ls -l

          # Dynamically get the repo name from GITHUB_REPOSITORY
          REPO_NAME=$(basename ${{ github.repository }})

          # Import repositories listed in the .repos file
          vcs import src < src/$REPO_NAME/ros2.repos

      - name: Setup ROS 2 Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install Package Dependencies with rosdep
        run: |
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build ROS 2 Workspace
        run: |
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run Tests
        run: |
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_direct+

      - name: Test Results Summary
        run: |
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon test-result --verbose
