name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Cache for Dependencies
        id: cache-ros  # Name this step so it can be referenced later
        uses: actions/cache@v3
        with:
          path: |
            /opt/ros/humble  # Cache installed ROS 2 packages
            ~/.ros           # Cache rosdep and other ROS-related configurations
            ~/ros2_ws/build  # Cache build artifacts
            ~/ros2_ws/install  # Cache installation
          key: ${{ runner.os }}-ros-humble-${{ hashFiles('**/package.xml') }}
          restore-keys: |
            ${{ runner.os }}-ros-humble-

      - name: Install ROS 2 Humble if Cache Missed
        if: steps.cache-ros.outputs.cache-hit != 'true'  # Correctly reference the cache step here
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep

          # Initialize rosdep
          sudo rosdep init
          rosdep update

      - name: Set up ROS 2 Workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cd ~/ros2_ws/src
          cp -r $GITHUB_WORKSPACE/* .
          git clone https://github.com/vortexntnu/vortex-msgs.git
          cd ~/ros2_ws

      - name: Install Package Dependencies with rosdep
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build ROS 2 Workspace
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          colcon build

      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          colcon test --event-handlers console_cohesion+

      - name: Test Results Summary
        run: |
          cd ~/ros2_ws
          colcon test-result --verbose
