name: Run clang-format Linter

on: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: "."
          exclude: "./lib"
          extensions: "h,cpp,c"
          clangFormatVersion: 18
          inplace: True
