name: codespell

on:
  pull_request:
     types: [review_requested, synchronize, opened, reopened]

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install codespell
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell

      - name: Run codespell to fix spelling mistakes
        run: |
          codespell -w .
