name: C++ Linter Pipeline

on: [push]

jobs:
  # First job: Run clang-format linter
  clang_format_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clang-format linter
        uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: "."
          exclude: "./lib"
          extensions: "h,cpp,c,hpp"
          clangFormatVersion: 18
          inplace: true

      - name: Commit clang-format changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Second job: Run cpp-linter, depends on clang-format linter completion
  cpp_linter_job:
    runs-on: ubuntu-latest
    needs: clang_format_linter  # Ensure this runs after clang-format linter job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run C++ Linter (cpp-linter)
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          verbosity: 'debug'  # Increase verbosity to see files being checked

      - name: List files to be linted
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \)
