name: C++ Linter Pipeline

on: 
  pull_request:

jobs:
  # First job: Run clang-format and commit formatting changes
  clang_format_linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository on the pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  # Checkout the pull request branch explicitly

      - name: Run clang-format linter
        uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: "."  # Lint the whole repository
          exclude: "./lib"  # Exclude the lib directory
          extensions: "h,cpp,c"  # Include header and C++ files
          clangFormatVersion: 18
          inplace: true  # Automatically format the files

      - name: Commit clang-format changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Second job: Run C++ linter (cpp-linter)
  cpp_linter_job:
    runs-on: ubuntu-latest
    needs: clang_format_linter  # This ensures the cpp-linter runs after clang-format

    steps:
      - name: Checkout repository on the updated branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Ensure it's the updated branch

      # Run the C++ linter (cpp-linter) with file annotations and thread comments
      - name: Run C++ Linter (cpp-linter)
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use the .clang-format config file from the repo
          tidy-checks: ''  # Use the .clang-tidy config file from the repo
          file-annotations: true  # Enable file annotations on specific lines with issues
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}  # Use thread comments for PR feedback

      # Fail fast if any lint checks failed
      - name: Fail fast if lint checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
