name: Lint and Format Check

# Trigger on push or pull request to the main branch
on: [push]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies (Clang, clang-tidy, and clang-format)
      - name: Install Clang and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy clang-format

      # Run clang-format to check formatting
      - name: Run clang-format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i
        shell: bash

      # Check if any changes were made by clang-format (indicating formatting issues)
      - name: Check for formatting changes
        run: git diff --exit-code
        shell: bash

      # Run clang-tidy to perform static analysis (linting)
      - name: Run clang-tidy
        run: |
          find . -name '*.cpp' | xargs clang-tidy
        shell: bash
