name: Linting Pipeline

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble  # Adjust ROS 2 distro as needed
    steps:
      - uses: actions/checkout@v3

      - name: Install ROS 2 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt-get update
          sudo apt-get install -y ros-${ROS_DISTRO}-desktop
          sudo apt-get install -y python3-pip python3-colcon-common-extensions clang-tidy
          python3 -m pip install -U colcon-compile-commands
          sudo rosdep init
          rosdep update

      - name: Install package dependencies
        run: |
          rosdep install --from-paths src --ignore-src -r -y

      - name: Source ROS 2 environment
        shell: bash -l {0}
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash

      - name: Build the workspace
        shell: bash -l {0}
        run: |
          colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Merge compile_commands.json files
        shell: bash -l {0}
        run: |
          colcon compile-commands merge

      - name: Run clang-tidy
        shell: bash -l {0}
        run: |
          find . -name '*.cpp' -o -name '*.cc' -o -name '*.cxx' | xargs -P$(nproc) -I{} clang-tidy {} -p .
