name: C++ Checks

on: [pull_request]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Install Eigen3
      - name: Install Eigen
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev

      # Step 3: Configure and build the project to generate compile_commands.json
      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make

      # Step 4: Run clang-tidy using the compile_commands.json
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'                          # Use .clang-format config file if available
          tidy-checks: ''                        # Use .clang-tidy config file if available
          database: build/compile_commands.json  # Pass the compilation database to clang-tidy
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      # Step 5: Fail fast if any linter checks fail
      - name: Fail fast if any linter checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1