name: Python Linter

on:
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Fail the build for any other errors, but ignore complexity issues
        flake8 . --count --max-complexity=10 --max-line-length=150 --ignore=C901,W503,E203 --statistics
    
