name: mypy

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust based on your Python version

      # Step 3: Install dependencies (including mypy)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy  # Or install from requirements.txt if needed

      # Step 4: Find changed files and run mypy
      - name: Run mypy on changed Python files
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.py')
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Python files changed."
            exit 0
          fi

          # Run mypy on each changed Python file
          for file in $CHANGED_FILES; do
            echo "Running mypy on $file"
            mypy "$file"
          done
