name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up ROS environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg2 lsb-release
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt-get update
          sudo apt-get install -y ros-humble-desktop python3-rosdep python3-colcon-common-extensions
          source /opt/ros/humble/setup.sh

      - name: Initialize rosdep
        run: |
          sudo rosdep init
          rosdep update

      - name: Install ROS Python dependencies
        run: |
          rosdep install --from-paths . --ignore-src -r -y

      - name: Set up Python environment and install pytest
        run: |
          sudo apt-get install -y python3-pip  # Ensure pip3 is installed
          pip3 install pytest                  # Install pytest
          python3 -m pytest --version          # Check if pytest is installed and display the version
          
      - name: Run pytest
        env:
          PYTHONPATH: $PYTHONPATH:/opt/ros/humble/lib/python3.10/site-packages
        run: |
          python3 -m pytest --maxfail=3 --disable-warnings  # Run pytest explicitly via python3
