name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up the ROS environment using ros-tooling/setup-ros
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble  # Replace with your ROS 2 distribution

      # Use action-ros-ci to build and test the workspace
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: my_package  # Change this to your ROS package name
          target-ros2-distro: humble  # Replace with your ROS 2 distribution
          skip-tests: false  # Set this to true if you want to skip tests

      # Install pytest if needed
      - name: Install pytest
        run: |
          pip3 install pytest

      # Run pytest tests
      - name: Run pytest
        env:
          PYTHONPATH: $PYTHONPATH:/opt/ros/humble/lib/python3.10/site-packages
        run: |
          pytest --maxfail=3 --disable-warnings
