name: Python Checks

on: [pull_request]

jobs:
  python_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install black isort bandit[toml] mypy pylint

      - name: Run black
        run: |
          black --check .

      - name: Run isort
        run: |
          isort --check .

      - name: Run bandit
        run: |
          bandit -c pyproject.toml -r . --severity-level medium

      - name: Run mypy
        run: |
          mypy . --explicit-package-bases

      - name: Run pylint
        run: |
          pylint .
