name: Reusable Industrial CI Workflow

on:
  workflow_call:
    inputs:
      ros_distro:
        description: "ROS Distribution (e.g., humble, jazzy)"
        required: false
        default: "humble"
        type: string
      os_name:
        description: "Operating System to run the workflow on"
        required: false
        default: "ubuntu-latest"
        type: string
      ref:
        description: "Git branch or tag to checkout"
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      vcs_repo_file_url:
        description: "URL to the vcs repositories file"
        required: false
        default: ""
        type: string
      skip_tests:
        description: "Skip running tests"
        required: false
        default: false
        type: boolean
      gcc_version:
        description: "GCC version to install"
        required: false
        default: "11"
        type: string
      dependency_script:
        description: "Path to a local script for managing dependencies not supported by rosdep or for pinning package versions"
        required: false
        default: ""
        type: string

jobs:
  industrial_ci:
    runs-on: ${{ inputs.os_name }}
    container:
      image: ros:${{ inputs.ros_distro }}-ros-base
    steps:
      - name: Set GCC and G++ version
        if: inputs.gcc_version != '11'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install gcc-${{ inputs.gcc_version }} g++-${{ inputs.gcc_version }} -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ inputs.gcc_version }} 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ inputs.gcc_version }} 60

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: 'ros-industrial/industrial_ci@master'
        env: 
          ROS_DISTRO: ${{ inputs.ros_distro }}
          ROS_REPO: main
          EXTERNAL_REPOS_URL: ${{ inputs.vcs_repo_file_url }}
          NOT_TEST_BUILD: ${{ inputs.skip_tests }}
          BEFORE_INIT: |
            if [ -f "${{ inputs.dependency_script }}" ]; then
              chmod +x ${{ inputs.dependency_script }}
              ./${{ inputs.dependency_script }}
            else
              echo "Dependency script not found, skipping."
            fi
