name: Source Build

on:
  workflow_dispatch:
  push:
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  source_build:
    name: Ubuntu 22.04 Build
    runs-on: ubuntu-22.04

    steps:
      - name: Setup ROS2 Humble Environment
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: humble

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up ROS2 Workspace
        run: |
          mkdir -p ros_ws/src
          mv * ros_ws/src/  # Move all files into src
          cd ros_ws/src
          vcs import --input ros2.repos

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions
          sudo rosdep init || echo "rosdep already initialized"
          rosdep update
          cd ros_ws
          rosdep install --from-paths src --ignore-src --rosdistro humble -r -y

      - name: Build ROS2 Workspace
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          colcon build --event-handlers console_cohesion+

      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-humble-ubuntu-22.04
          path: ros_ws/log
