name: Source Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '03 3 * * *'

jobs:
  source_build:
    name: Ubuntu 22.04 Build
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Set up the ROS2 environment (this installs ROS2, colcon, rosdep, vcs, etc.)
      - name: Setup ROS2 Humble Environment
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: humble

      # Step 2: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: .

      # Step 3: Set up the workspace and import any external repositories using the .repos file
      - name: Set Up ROS2 Workspace
        run: |
          # Create the workspace directories
          mkdir -p ~/ros2_ws/src
          
          # Move the contents of the cloned repository into a folder named after the repository
          repo_name=$(basename $(pwd))
          mv $(ls -A | grep -v '^ros2_ws$') ~/ros2_ws/src/$repo_name
          
          # Change directory to src and import any external repositories from the .repos file
          cd ~/ros2_ws/src
          if [ -f $repo_name/ros2.repos ]; then
            vcs import < $repo_name/ros2.repos
          fi


      # Step 4: Install additional dependencies using rosdep
      - name: Install Dependencies
        run: |
          cd ~/ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro humble -r -y

      # Step 5: Build the ROS2 workspace
      - name: Build ROS2 Workspace
        run: |
          cd ~/ros2_ws
          colcon build --event-handlers console_cohesion+

      # Step 6: Run tests on the workspace
      - name: Run Tests
        run: |
          cd ~/ros2_ws
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose

      # Step 7: Upload the build logs as an artifact
      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-humble-ubuntu-22.04
          path: ros_ws/log
