name: Source Build with Reusable Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: kluge7/test3/.github/workflows/reusable-source-build.yaml@main  # Replace 'your-username' with your GitHub username
    with:
      ros_distro: 'humble'       # Specify the ROS 2 distribution (or leave it to use default 'humble')
      os_name: 'ubuntu-22.04'    # Specify the OS (or leave it to use default 'ubuntu-22.04')
      ref: 'feature-branch'      # Specify the branch to checkout (or leave it to use default 'main')
    secrets:
      token: ${{ secrets.MY_SECRET }}   # Use the stored secret for the Personal Access Token