name: Source Build on Push
# GitHub Actions workflow to build all ROS 2 packages from source on push.

on:
  push:
    branches:
      - '**'  # Runs on any branch push event

jobs:
  build:
    runs-on: ubuntu-22.04  # Default OS, can be overridden via env

    env:
      ROS_DISTRO: humble  # Default ROS distro, can be overridden via env
      OS_NAME: ubuntu-22.04  # Default OS name, can be overridden via env
      REF: ${{ github.ref }}  # Git branch to checkout (from push event)
      VCS_REPO_FILE_URL: 'https://github.com/vortexntnu/vortex-auv/blob/main/ros2.repos'  # Default empty for no repos file
      SKIP_TESTS: 'false'  # Default to false, set to true to skip tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: src/${{ github.event.repository.name }}
          ref: ${{ env.REF }}

      - name: Setup ROS 2 Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}

      - name: Build and Test ROS 2 Packages
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          vcs-repo-file-url: ${{ env.VCS_REPO_FILE_URL }}
          skip-tests: ${{ env.SKIP_TESTS }}
