name: Reusable Update Pre-commit
# Automatically updates the pre-commit config and shows changes if detected

on: [push]

jobs:
  auto_update_and_fail_if_changes:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pre-commit
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pre-commit

      - name: Auto-update pre-commit hooks
        run: |
          source .venv/bin/activate
          pre-commit autoupdate

      - name: Check for changes
        id: git_status
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: There are changes
        if: env.changes_detected == 'true'
        run: |
          git diff --exit-code || true

      - name: No changes!
        if: env.changes_detected != 'true'
        run: |
          echo "No changes detected"
