name: Pre-commit Checks
# Runs pre-commit checks on push

on:
  push:
    branches:
      - main  # Or any other branches you want to include

jobs:
  pre-commit:
    runs-on: ubuntu-22.04  # OS is hardcoded now

    env:
      WORKSPACE_PATH: ${{ github.workspace }}/vortex_ws

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORKSPACE_PATH }}/src/${{ github.event.repository.name }}
          ref: ${{ github.ref }}  # Automatically uses the branch that triggered the push

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
