name: Reusable Update Pre-commit
# Automatically runs pre-commit hooks on all files and fails if there are issues

on: [push]

jobs:
  auto_run_pre_commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pre-commit
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pre-commit

      - name: Run pre-commit hooks on all files
        run: |
          source .venv/bin/activate
          pre-commit run --all-files
