name: Reusable Update Pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all history is fetched for pre-commit hooks

      # Set up Python (if your pre-commit hooks require a specific Python version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      # Cache pre-commit environments to speed up subsequent runs
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      # Install and run pre-commit hooks
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        with:
          # Pass additional arguments if needed
          extra_args: --all-files
