name: Industrial CI

on:
  workflow_call:
    inputs:
      os:
        description: "Operating System to run the workflow on"
        required: false
        default: "ubuntu-22.04"
        type: string
      ros_distro:
        description: "List of ROS distributions to test (JSON array)"
        required: false
        default: '["humble"]'
        type: string
      ros_repo:
        description: "List of ROS repositories to test (JSON array)"
        required: false
        default: '["main"]'
        type: string
      upstream_workspace:
        description: "URL to the upstream workspace file"
        required: false
        default: ""
        type: string
      skip_tests:
        description: "Skip running tests"
        required: false
        default: false
        type: boolean
      compiler_version:
        description: "Compiler version (e.g., 11)"
        required: false
        default: "13"
        type: string

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: ${{ fromJson(inputs.ros_distro) }}
        ROS_REPO: ${{ fromJson(inputs.ros_repo) }}
    env:
      ADDITIONAL_DEBS: "gcc-${{ inputs.compiler_version }} g++-${{ inputs.compiler_version }}"
      CC: "gcc-${{ inputs.compiler_version }}"
      CXX: "g++-${{ inputs.compiler_version }}"
      BEFORE_INIT: |
        apt-get update && apt-get install -y gcc-${{ inputs.compiler_version }} g++-${{ inputs.compiler_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
          UPSTREAM_WORKSPACE: ${{ inputs.upstream_workspace }}
          NOT_TEST_BUILD: ${{ inputs.skip_tests }}
