name: Validation Tools

on: []

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code after formatting has been applied
      - uses: actions/checkout@v2

      # Install mypy and run type checking (or any other validation)
      - name: Install mypy and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mypy

      # Run mypy to perform type checking on the Python code
      - name: Run mypy type checking
        run: |
          mypy . --explicit-package-bases
