name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permissions for requirements.sh
        run: chmod +x requirements.sh
      - uses: 'ros-industrial/industrial_ci@master'
        env: 
          ROS_DISTRO: humble
          ROS_REPO: main
          UPSTREAM_WORKSPACE: 'https://raw.githubusercontent.com/vortexntnu/vortex-auv/main/ros2.repos'
          BEFORE_INIT: './requirements.sh'