name: Formatting Tools

on: []

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Run clang-format to check and fix C/C++ code formatting
      - uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: "."
          exclude: "./lib"
          extensions: "h,cpp,c"
          clangFormatVersion: 18
          inplace: True

      # Commit clang-format changes if needed
      - name: Commit clang-format changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install and run codespell to fix spelling mistakes
      - name: Install and run codespell
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell
          codespell -w .

      # Commit codespell changes if needed
      - name: Commit codespell fixes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Codespell Robot
          author_email: codespell-robot@example.com
          message: "Committing codespell fixes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
